services:
  - type: web
    name: smartshield-whois-api
    env: python
    region: oregon
    plan: free
    branch: user-dashboard
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 --threads 4 --timeout 120 wsgi:app
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SERVICE_ROLE_KEY
        sync: false
      - key: PYTHON_VERSION
        value: 3.10.0
